version: "3"

services:
  nginx:
    build: ./nginx
    ports:
    - "80:80"
    volumes:
      - ./web_app/static_root:/code/static_root
      - ./web_app/media:/code/media
      - ./nginx/logs:/var/log/nginx
    depends_on:
      - db
      - web

  web:
    build: ./web_app
    env_file: ./web.env
    command: /code/run.sh
    volumes:
      - ./web_app:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis_q

  redis_q:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    restart: always

  db:
    image: postgres
    env_file: ./web.env
    ports:
      - "5432:5432"