services:
  nginx:
    build: ./nginx
    ports:
    - "8002:80"
    volumes:
      - ./web_app/static_root:/code/static_root
      - ./web_app/media:/code/media

  web:
    build: ./web_app
    env_file: ./web.env
    command: /code/run.sh
    volumes:
      - ./web_app:/code
    ports:
      - "8001:8000"
  db:
    image: postgres
    env_file: ./web.env
    ports:
      - "5455:5432"