# Generated by Django 3.2.9 on 2021-12-14 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='author',
        ),
        migrations.AddField(
            model_name='comment',
            name='article',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='news.article'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='email',
            field=models.EmailField(default='f', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='nickname',
            field=models.CharField(default='a', max_length=200),
            preserve_default=False,
        ),
    ]
