# Generated by Django 3.2.9 on 2021-12-14 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20211214_0912'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comment',
            new_name='Mention',
        ),
    ]
