# Generated by Django 3.2.9 on 2021-12-14 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_comment_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ('-created',)},
        ),
        migrations.RemoveField(
            model_name='project',
            name='slug',
        ),
    ]
