# Generated by Django 3.2.9 on 2022-01-03 21:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0010_comment_is_moderated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mention',
            name='author_position',
        ),
        migrations.AlterField(
            model_name='mention',
            name='author',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mention', to=settings.AUTH_USER_MODEL),
        ),
    ]
