# Generated by Django 3.2.9 on 2022-01-03 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_auto_20220103_2128'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mention',
        ),
    ]
